"""
Script generation agent using Google Gemini.
Generates structured sports broadcast scripts from research context.

NO HARDCODED DATA - All scripts are dynamically generated by Gemini.
"""
import os
import json
from typing import Optional
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

import google.generativeai as genai
from models import (
    SportsNarrativeScript, 
    ResearchContext,
    StudioSetting,
    Host,
    ScriptSegment,
    AIGeneratedSegment,
    RealClipReference,
    DialogueLine,
    Mood
)


class ScriptGenerator:
    """
    Generates sports broadcast scripts using Gemini.
    All scripts are dynamically generated - no hardcoded templates.
    """
    
    def __init__(self):
        api_key = os.getenv("GOOGLE_API_KEY") or os.getenv("GEMINI_API_KEY")
        if not api_key:
            raise ValueError(
                "No API key found! Set GOOGLE_API_KEY or GEMINI_API_KEY environment variable.\n"
                "Get your API key at: https://aistudio.google.com/app/apikey"
            )
        
        genai.configure(api_key=api_key)
        self.model = genai.GenerativeModel('gemini-2.0-flash')
        print("[ScriptGenerator] ✅ Gemini API configured")
    
    def _get_system_prompt(self) -> str:
        """System prompt for script generation."""
        return """You are an expert sports broadcast scriptwriter for a primetime ESPN-style analysis show.
Your task is to create compelling, dramatic scripts that blend AI-generated studio segments with real sports footage clips.

The script should feel like a high-production sports documentary/analysis show with:
- Dramatic narrative tension and pacing
- Expert analysis and heated debate between hosts
- Emotional storytelling that connects with viewers
- Strategic use of real game footage clips interspersed with studio segments
- Professional broadcast quality dialogue

You create scripts for AI video generation (like Veo), so visual descriptions must be detailed and specific.

IMPORTANT: You must return ONLY valid JSON matching the exact schema provided. No markdown, no explanations, just the JSON object."""

    def _get_script_prompt(self, research: ResearchContext, duration_seconds: int = 150) -> str:
        """Create the prompt for script generation."""
        return f"""Generate a {duration_seconds}-second sports broadcast script for this storyline:

STORYLINE: {research.original_prompt}

RESEARCH SUMMARY:
{research.storyline_summary}

KEY FACTS:
{json.dumps(research.key_facts, indent=2)}

KEY FIGURES:
{json.dumps(research.key_figures, indent=2)}

TIMELINE:
{json.dumps(research.timeline, indent=2)}

CONTROVERSY POINTS:
{json.dumps(research.controversy_points, indent=2)}

EMOTIONAL ANGLES:
{json.dumps(research.emotional_angles, indent=2)}

---

Generate a complete JSON script with this EXACT structure:
{{
    "title": "Compelling episode title that captures the drama",
    "storyline": "{research.original_prompt}",
    "total_duration_seconds": {duration_seconds},
    "studio": {{
        "description": "Detailed studio description for AI video generation - describe the set, furniture, screens, atmosphere",
        "lighting": "Specific lighting setup - mood, color temperature, shadows, accents",
        "background_elements": ["Large LED screen showing relevant footage", "Sports graphics", "Team logos", "Ticker"],
        "color_scheme": "Primary and accent colors that match the story mood",
        "time_of_day": "When the show is airing (affects lighting mood)"
    }},
    "hosts": [
        {{
            "name": "Create a unique host name",
            "role": "Lead Anchor",
            "appearance": "Detailed physical description for AI video generation - age, ethnicity, clothing, demeanor",
            "position": "Center desk, facing camera"
        }},
        {{
            "name": "Create another unique host name",
            "role": "NFL Analyst", 
            "appearance": "Detailed physical description - make them visually distinct from other hosts",
            "position": "Left side of desk"
        }},
        {{
            "name": "Create a third host name",
            "role": "Former Player / Expert Analyst",
            "appearance": "Detailed physical description - athletic build, specific clothing",
            "position": "Right side of desk"
        }}
    ],
    "premise": "The narrative premise - what angle are we taking on this story? What's the hook?",
    "key_points": ["Main point 1 to cover", "Main point 2", "Main point 3", "Main point 4"],
    "segments": [
        {{
            "order": 1,
            "segment_type": "ai_generated",
            "ai_segment": {{
                "segment_id": "intro_1",
                "segment_type": "intro",
                "duration_seconds": 25,
                "mood": "dramatic",
                "visual_description": "Detailed visual scene description for AI video generation - camera angles, host positions, background activity, graphics on screen",
                "camera_notes": "Specific camera directions - push in, pan, cut patterns",
                "dialogue": [
                    {{
                        "speaker": "Host Name",
                        "text": "The actual dialogue they speak - make it dramatic, engaging, professional",
                        "delivery": "How they deliver it - tone, emotion, gestures",
                        "camera_direction": "Camera angle for this line"
                    }}
                ],
                "graphics": ["LOWER THIRD: Show title", "Any on-screen graphics"]
            }},
            "clip_reference": null
        }},
        {{
            "order": 2,
            "segment_type": "real_clip",
            "ai_segment": null,
            "clip_reference": {{
                "clip_id": "clip_1",
                "description": "Detailed description of what the real sports clip should show",
                "search_query": "Specific YouTube/archive search query to find this clip",
                "duration_seconds": 8,
                "context": "Why this clip is important to the narrative at this moment",
                "transition_in": "How to transition into clip (fade, cut, dramatic)",
                "transition_out": "How to transition out"
            }}
        }}
    ],
    "research_sources": ["List the sources from the research"]
}}

REQUIREMENTS:
1. Create 6-8 segments alternating between ai_generated and real_clip types
2. Start with a dramatic intro segment, end with a powerful outro
3. Include at least one debate segment where hosts disagree
4. Make dialogue natural but dramatic - this is primetime sports TV
5. Clip search queries should be specific enough to find real footage on YouTube
6. Visual descriptions must be detailed enough for AI video generation
7. Use these mood values: dramatic, exciting, somber, celebratory, tense, reflective, controversial
8. Use these segment types for ai_segment: intro, analysis, debate, transition, outro
9. Total duration of all segments should approximately equal {duration_seconds} seconds
10. Make it feel like a real ESPN/Fox Sports production

Return ONLY the JSON object, no other text or markdown."""

    def generate_script_sync(
        self, 
        research: ResearchContext, 
        duration_seconds: int = 150
    ) -> SportsNarrativeScript:
        """
        Generate a complete broadcast script from research context.
        Uses Gemini to dynamically create the entire script.
        """
        print(f"\n[ScriptGenerator] 📝 Generating {duration_seconds}s script...")
        print(f"[ScriptGenerator] Storyline: {research.original_prompt}")
        
        try:
            prompt = self._get_script_prompt(research, duration_seconds)
            
            response = self.model.generate_content(
                [self._get_system_prompt(), prompt],
                generation_config=genai.GenerationConfig(
                    response_mime_type="application/json",
                    temperature=0.85,  # Slightly higher for creativity
                )
            )
            
            # Parse the JSON response
            script_data = self._parse_json_response(response.text)
            
            # Validate and create the Pydantic model
            script = SportsNarrativeScript(**script_data)
            
            print(f"[ScriptGenerator] ✅ Script generated!")
            print(f"   - Title: {script.title}")
            print(f"   - {len(script.segments)} segments")
            print(f"   - {len(script.hosts)} hosts")
            print(f"   - Total duration: {script.total_duration_seconds}s")
            
            return script
            
        except Exception as e:
            print(f"[ScriptGenerator] ❌ Error generating script: {e}")
            import traceback
            traceback.print_exc()
            raise RuntimeError(f"Script generation failed: {e}")
    
    def _parse_json_response(self, response_text: str) -> dict:
        """Parse JSON from Gemini response, handling potential issues."""
        text = response_text.strip()
        
        # Remove markdown code blocks if present
        if "```json" in text:
            json_start = text.find("```json") + 7
            json_end = text.find("```", json_start)
            text = text[json_start:json_end]
        elif "```" in text:
            json_start = text.find("```") + 3
            json_end = text.find("```", json_start)
            text = text[json_start:json_end]
        
        try:
            return json.loads(text.strip())
        except json.JSONDecodeError as e:
            print(f"[ScriptGenerator] JSON parsing failed: {e}")
            print(f"[ScriptGenerator] Raw response:\n{response_text[:1000]}...")
            raise ValueError(f"Failed to parse script JSON: {e}")

    async def generate_script(
        self, 
        research: ResearchContext, 
        duration_seconds: int = 150
    ) -> SportsNarrativeScript:
        """
        Async version of script generation.
        """
        # For now, just call the sync version
        # TODO: Implement proper async with aiohttp or similar
        return self.generate_script_sync(research, duration_seconds)


# Create singleton instance - will raise error if no API key
script_generator = ScriptGenerator()
